"""initial schema

Revision ID: 63a5757f19c7
Revises: 
Create Date: 2026-06-11 12:03:43.248327
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database  # GUID() custom type used in column definitions


# revision identifiers, used by Alembic.
revision: str = '63a5757f19c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plans',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('sessions_included', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cancellation_policies',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('free_cancellation_hours', sa.Integer(), nullable=False),
    sa.Column('late_charge_percent', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('promo_codes',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('percent_off', sa.Integer(), nullable=True),
    sa.Column('amount_off_cents', sa.Integer(), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('times_redeemed', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('subjects',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('admin_actions',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('admin_id', app.database.GUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', app.database.GUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_connections',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('user_id', app.database.GUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token_enc', sa.String(), nullable=False),
    sa.Column('refresh_token_enc', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('student_id', app.database.GUID(), nullable=False),
    sa.Column('tutor_id', app.database.GUID(), nullable=False),
    sa.Column('student_unread_count', sa.Integer(), nullable=False),
    sa.Column('tutor_unread_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'tutor_id', name='uq_conversation_pair')
    )
    op.create_table('notifications',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('user_id', app.database.GUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_methods',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('user_id', app.database.GUID(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('last4', sa.String(), nullable=True),
    sa.Column('exp_month', sa.Integer(), nullable=True),
    sa.Column('exp_year', sa.Integer(), nullable=True),
    sa.Column('stripe_payment_method_id', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('user_id', app.database.GUID(), nullable=False),
    sa.Column('grade_level', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('student_id', app.database.GUID(), nullable=False),
    sa.Column('plan_id', app.database.GUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['billing_plans.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutor_profiles',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('user_id', app.database.GUID(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('hourly_rate_cents', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('stripe_account_id', sa.String(), nullable=True),
    sa.Column('vetting_status', sa.String(), nullable=False),
    sa.Column('avg_rating', sa.Integer(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('availability_exceptions',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('tutor_id', app.database.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=True),
    sa.Column('end_minute', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('conversation_id', app.database.GUID(), nullable=False),
    sa.Column('sender_id', app.database.GUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payouts',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('tutor_id', app.database.GUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stripe_transfer_id', sa.String(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('student_id', app.database.GUID(), nullable=False),
    sa.Column('tutor_id', app.database.GUID(), nullable=False),
    sa.Column('subject_id', app.database.GUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('video_room_url', sa.String(), nullable=True),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutor_availability',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('tutor_id', app.database.GUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutor_credentials',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('tutor_id', app.database.GUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutor_id_verification',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('tutor_id', app.database.GUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id')
    )
    op.create_table('tutor_subjects',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('tutor_id', app.database.GUID(), nullable=False),
    sa.Column('subject_id', app.database.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id', 'subject_id', name='uq_tutor_subject')
    )
    op.create_table('tutor_teaching_approach',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('tutor_id', app.database.GUID(), nullable=False),
    sa.Column('philosophy', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.String(), nullable=True),
    sa.Column('specialties', sa.Text(), nullable=True),
    sa.Column('sample_lesson_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id')
    )
    op.create_table('tutor_vetting',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('tutor_id', app.database.GUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('background_check_status', sa.String(), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id')
    )
    op.create_table('payments',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('session_id', app.database.GUID(), nullable=True),
    sa.Column('student_id', app.database.GUID(), nullable=False),
    sa.Column('tutor_id', app.database.GUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('platform_fee_cents', sa.Integer(), nullable=False),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stripe_payment_intent', sa.String(), nullable=True),
    sa.Column('promo_code_id', app.database.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('session_id', app.database.GUID(), nullable=False),
    sa.Column('tutor_id', app.database.GUID(), nullable=False),
    sa.Column('student_id', app.database.GUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('tutor_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('session_flags',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('session_id', app.database.GUID(), nullable=False),
    sa.Column('reporter_id', app.database.GUID(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_materials',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('session_id', app.database.GUID(), nullable=False),
    sa.Column('uploader_id', app.database.GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disputes',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('session_id', app.database.GUID(), nullable=True),
    sa.Column('payment_id', app.database.GUID(), nullable=True),
    sa.Column('raised_by_id', app.database.GUID(), nullable=False),
    sa.Column('against_id', app.database.GUID(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('refund_amount_cents', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['against_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disputes')
    op.drop_table('session_materials')
    op.drop_table('session_flags')
    op.drop_table('reviews')
    op.drop_table('payments')
    op.drop_table('tutor_vetting')
    op.drop_table('tutor_teaching_approach')
    op.drop_table('tutor_subjects')
    op.drop_table('tutor_id_verification')
    op.drop_table('tutor_credentials')
    op.drop_table('tutor_availability')
    op.drop_table('sessions')
    op.drop_table('payouts')
    op.drop_table('messages')
    op.drop_table('availability_exceptions')
    op.drop_table('tutor_profiles')
    op.drop_table('subscriptions')
    op.drop_table('student_profiles')
    op.drop_table('payment_methods')
    op.drop_table('notifications')
    op.drop_table('conversations')
    op.drop_table('calendar_connections')
    op.drop_table('admin_actions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('promo_codes')
    op.drop_table('cancellation_policies')
    op.drop_table('billing_plans')
    # ### end Alembic commands ###
